### ISSUE TITLE
Incompatible with Rails 6

### ISSUE THREAD

**Issue by sedubois** [SourceLabsLLC/administrate_collapsible_navigation#6]
The gem is not compatible with Rails 6:
```rb
s.add_dependency 'rails', '>= 4.2', '< 6.0'
```

Would it be possible to either update it or mark it as deprecated?

Thanks 😊

**Comment by andreibondarev** [comment]
@sedubois Would you like to issue a PR?

**Comment by sedubois** [comment]
Yes, see #7

**Comment by andreibondarev** [comment]
@sedubois Thank you!

**Comment by andreibondarev** [comment]
@sedubois Fixed!
