### ISSUE TITLE
ActionView::Template::Error with Rails 6.1.3.2

### ISSUE THREAD

**Issue by sedubois** [SourceLabsLLC/administrate_collapsible_navigation#8]
```
     ActionView::Template::Error:
       Please use symbols for polymorphic route arguments.
```

See https://github.com/thoughtbot/administrate/issues/1971 and https://github.com/thoughtbot/administrate/pull/1972 for details.

**Comment by andreibondarev** [comment]
@sedubois Would you please be able to send a PR to fix this?

**Comment by sedubois** [comment]
At the moment I have stopped using this gem, but sure I’ll provide a PR if I resume using it. Thanks!
